/** Keep in sync with `lib/sleepPostSelect.ts` in the mobile app. */
export const SLEEP_POST_FEED_SELECT = [
  'id',
  'user_id',
  'title',
  'asleep_minutes',
  'in_bed_minutes',
  'core_minutes',
  'deep_minutes',
  'rem_minutes',
  'awake_minutes',
  'awake_events',
  'raw_samples',
  'session_breakdown',
  'source_device',
  'bedtime',
  'wake_time',
  'sleep_date',
  'vibe',
  'tags',
  'dream_log',
  'dream_mood',
  'photo_urls',
  'photo_thumb_urls',
  'blur_dream',
  'morning_notes',
  'is_private',
  'created_at',
  'location_label',
  'is_custom',
].join(', ');
