import type {
  AnalyticsFilters,
  CatalogListFilters,
  ChallengeListFilters,
  DataIssueFilters,
  PremiumUserFilters,
  ReportListFilters,
  UserSearchFilters,
} from '../lib/admin';
import type { PaginationFilters } from '../lib/adminPagination';

export const queryKeys = {
  feed: ['feed'] as const,
  post: (id: string) => ['post', id] as const,
  profile: (userId: string) => ['profile', userId] as const,
  userPosts: (userId: string) => ['user-posts', userId] as const,
  challenges: (statusKey: string) => ['challenges', statusKey] as const,
  challenge: (id: string) => ['challenge', id] as const,
  friends: ['friends'] as const,
  friendRequests: ['friend-requests'] as const,
  clubs: ['clubs'] as const,
  clubMembers: (clubId: string) => ['club-members', clubId] as const,
  search: (query: string) => ['search', query] as const,
  comparePeriods: (userId: string) => ['compare-periods', userId] as const,
  userStats: (userId: string) => ['user-stats', userId] as const,
  lifetimeStats: (userId: string) => ['lifetime-stats', userId] as const,
  challengeProgress: (id: string) => ['challenge-progress', id] as const,
  challengeContributions: (id: string) => ['challenge-contributions', id] as const,
  postKudos: (postId: string) => ['post-kudos', postId] as const,
  postComments: (postId: string) => ['post-comments', postId] as const,
  tags: ['tags'] as const,
  avatarRoleStyles: ['avatar-role-styles'] as const,
  assignableRoles: ['assignable-roles'] as const,
  isModerator: ['is-moderator'] as const,
  admin: {
    all: ['admin'] as const,
    dashboard: ['admin', 'dashboard'] as const,
    postReportsQueue: ['admin', 'post-reports', 'queue'] as const,
    commentReportsQueue: ['admin', 'comment-reports', 'queue'] as const,
    postReportsPage: (filters: ReportListFilters) => ['admin', 'post-reports', 'page', filters] as const,
    commentReportsPage: (filters: ReportListFilters) => ['admin', 'comment-reports', 'page', filters] as const,
    tags: (filters: CatalogListFilters = {}) => ['admin', 'tags', filters] as const,
    roleDefinitions: (filters: CatalogListFilters = {}) => ['admin', 'role-definitions', filters] as const,
    appVersions: ['admin', 'app-versions'] as const,
    analyticsMetrics: (filters: AnalyticsFilters) => ['admin', 'analytics', 'metrics', filters] as const,
    analyticsActivity: (filters: AnalyticsFilters) => ['admin', 'analytics', 'activity', filters] as const,
    analyticsUsers: (filters: AnalyticsFilters) => ['admin', 'analytics', 'users', filters] as const,
    analyticsPosts: (filters: AnalyticsFilters) => ['admin', 'analytics', 'posts', filters] as const,
    recentPosts: (filters: AnalyticsFilters) => ['admin', 'posts', 'list', filters] as const,
    postsPageMetrics: (filters: AnalyticsFilters) => ['admin', 'posts', 'metrics', filters] as const,
    postsPageActivity: (filters: AnalyticsFilters) => ['admin', 'posts', 'activity', filters] as const,
    analyticsTags: (filters: AnalyticsFilters) => ['admin', 'analytics', 'tags', filters] as const,
    userSearch: (filters: UserSearchFilters) => ['admin', 'user-search', filters] as const,
    premiumMetrics: ['admin', 'premium', 'metrics'] as const,
    premiumUsers: (filters: PremiumUserFilters) => ['admin', 'premium', 'users', filters] as const,
    healthMetrics: (days: number) => ['admin', 'health', days] as const,
    cohortRetention: (weeks: number) => ['admin', 'cohort', weeks] as const,
    communityMetrics: ['admin', 'community', 'metrics'] as const,
    challenges: (filters: ChallengeListFilters) => ['admin', 'community', 'challenges', filters] as const,
    clubs: (filters: PaginationFilters) => ['admin', 'community', 'clubs', filters] as const,
    dataIssues: (filters: DataIssueFilters) => ['admin', 'data-issues', filters] as const,
    userDetail: (userId: string) => ['admin', 'user-detail', userId] as const,
    userPosts: (filters: AnalyticsFilters) => ['admin', 'user-posts', filters] as const,
  },
};
